# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_foodOptimizer.ui'
#
# Created: Sun Mar 30 18:49:52 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(880, 661)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox_categories = QtGui.QComboBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_categories.sizePolicy().hasHeightForWidth())
        self.comboBox_categories.setSizePolicy(sizePolicy)
        self.comboBox_categories.setMinimumSize(QtCore.QSize(180, 0))
        self.comboBox_categories.setMaximumSize(QtCore.QSize(500000, 16777215))
        self.comboBox_categories.setObjectName("comboBox_categories")
        self.horizontalLayout.addWidget(self.comboBox_categories)
        self.lineEdit_search = QtGui.QLineEdit(self.tab)
        self.lineEdit_search.setMaximumSize(QtCore.QSize(2000000, 16777215))
        self.lineEdit_search.setObjectName("lineEdit_search")
        self.horizontalLayout.addWidget(self.lineEdit_search)
        self.pushButton_search = QtGui.QPushButton(self.tab)
        self.pushButton_search.setMaximumSize(QtCore.QSize(1000000, 16777215))
        self.pushButton_search.setObjectName("pushButton_search")
        self.horizontalLayout.addWidget(self.pushButton_search)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.splitter_2 = QtGui.QSplitter(self.tab)
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter = QtGui.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tableWidget_overview = QtGui.QTableWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_overview.sizePolicy().hasHeightForWidth())
        self.tableWidget_overview.setSizePolicy(sizePolicy)
        self.tableWidget_overview.setMinimumSize(QtCore.QSize(250, 200))
        self.tableWidget_overview.setMaximumSize(QtCore.QSize(2000000, 2000000))
        self.tableWidget_overview.setObjectName("tableWidget_overview")
        self.tableWidget_overview.setColumnCount(0)
        self.tableWidget_overview.setRowCount(0)
        self.mpl_widget = MatplotlibWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_widget.sizePolicy().hasHeightForWidth())
        self.mpl_widget.setSizePolicy(sizePolicy)
        self.mpl_widget.setMinimumSize(QtCore.QSize(200, 200))
        self.mpl_widget.setObjectName("mpl_widget")
        self.tableWidget_userSelection = QtGui.QTableWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_userSelection.sizePolicy().hasHeightForWidth())
        self.tableWidget_userSelection.setSizePolicy(sizePolicy)
        self.tableWidget_userSelection.setMinimumSize(QtCore.QSize(500, 200))
        self.tableWidget_userSelection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tableWidget_userSelection.setObjectName("tableWidget_userSelection")
        self.tableWidget_userSelection.setColumnCount(0)
        self.tableWidget_userSelection.setRowCount(0)
        self.horizontalLayout_2.addWidget(self.splitter_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMaximumSize(QtCore.QSize(160, 16777215))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_singleMeal = QtGui.QRadioButton(self.frame)
        self.radioButton_singleMeal.setChecked(True)
        self.radioButton_singleMeal.setObjectName("radioButton_singleMeal")
        self.verticalLayout_2.addWidget(self.radioButton_singleMeal)
        self.radioButton_oneDay = QtGui.QRadioButton(self.frame)
        self.radioButton_oneDay.setObjectName("radioButton_oneDay")
        self.verticalLayout_2.addWidget(self.radioButton_oneDay)
        self.radioButton_sevenDays = QtGui.QRadioButton(self.frame)
        self.radioButton_sevenDays.setObjectName("radioButton_sevenDays")
        self.verticalLayout_2.addWidget(self.radioButton_sevenDays)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.pushButton_startOptimization = QtGui.QPushButton(self.frame)
        self.pushButton_startOptimization.setMaximumSize(QtCore.QSize(160, 16777215))
        self.pushButton_startOptimization.setObjectName("pushButton_startOptimization")
        self.verticalLayout_3.addWidget(self.pushButton_startOptimization)
        self.verticalLayout_4.addWidget(self.frame)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 880, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search.setText(QtGui.QApplication.translate("MainWindow", "suchen", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_singleMeal.setText(QtGui.QApplication.translate("MainWindow", "Einzelne Mahlzeit", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_oneDay.setText(QtGui.QApplication.translate("MainWindow", "1 Tag", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_sevenDays.setText(QtGui.QApplication.translate("MainWindow", "7 Tage", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_startOptimization.setText(QtGui.QApplication.translate("MainWindow", "Start Optimierung", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "optimization", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "log", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Hilfe", None, QtGui.QApplication.UnicodeUTF8))

from matplotlibwidget import MatplotlibWidget
